In [1]:
import pandas as pd
import os

root = "./datasets/indicators/"

merged_df = pd.DataFrame()
first = True

for file in os.listdir(root):
    print(file)
    metric_df = pd.read_csv(root + file)

    if first:
        merged_df['company_name'] = metric_df['company_name']
        first = False

    metric_df = metric_df.drop(metric_df[~metric_df['company_name'].isin(merged_df['company_name'])] .index)
    merged_df = pd.merge(merged_df, metric_df, on='company_name', how="outer")

merged_df.to_csv('./datasets/overall_indicators.csv', index=False)
merged_df

email_validation.csv
phone_validation.csv
price_details.csv
registered.csv
trustpilot_scores.csv

,company_name,email_invalid,phone_invalid,num_matches,num_jumps,max_change,registered_name,is_registered,trustpilot_score,score_category,is_reviewed
0,#nomad travel,True,False,3.0,2.0,74.747475,NaN,False,3.1,3-4,True
1,*everything genetic ltd,False,False,3.0,3.0,30.696670,NaN,False,NaN,No Score,False
2,+001 expert covid testing uk,False,False,5.0,1.0,550.000000,NaN,False,3.1,3-4,True
3,+247 travel tests,False,False,2.0,3.0,70.930233,NaN,False,2.7,2-3,True
4,+44 covid test,False,False,4.0,5.0,74.747475,NaN,False,1.5,1-2,True
...,...,...,...,...,...,...,...,...,...,...,...
716,zava,False,False,1.0,0.0,0.000000,NaN,False,4.8,4-5,True
717,zen healthcare,False,False,4.0,2.0,42.750000,zen healthcare services ltd,True,NaN,NaN,NaN
718,zen healthcare (purecare ltd),False,False,3.0,2.0,41.779661,NaN,False,NaN,NaN,NaN
719,zoomdoc,True,False,2.0,2.0,26.595745,zoomdoctor limited,True,NaN,NaN,NaN
720,zoomdoc health,True,False,2.0,2.0,26.595745,NaN,False,NaN,NaN,NaN